AtlasLoot_BonusRoll_Items[87018]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87146]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89256]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86315]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85356]={[11]={false,false,false,true},}
AtlasLoot_BonusRoll_Items[89768]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86763]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84845]={[7]={true,false,false},}
AtlasLoot_BonusRoll_Items[86955]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87019]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[87147]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89257]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[90408]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86764]={[2]={true,false,false},[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[84846]={[5]={true,true,false},}
AtlasLoot_BonusRoll_Items[86956]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[85997]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87148]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89258]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[90409]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85358]={[11]={false,false,false,true},}
AtlasLoot_BonusRoll_Items[86765]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86829]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[84847]={[7]={false,false,true},}
AtlasLoot_BonusRoll_Items[86957]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87021]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87149]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89259]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86318]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86766]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86894]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86958]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87022]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86127]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89260]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[90411]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86383]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86767]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89964]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86959]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87023]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86128]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89261]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[85297]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86384]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86768]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89965]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86960]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87024]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86129]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89262]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86321]={[10]={true,false,true},[11]={false,true,true,false},}
AtlasLoot_BonusRoll_Items[86385]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86513]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86769]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[89966]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86961]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87025]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86130]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89263]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[86322]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[85363]={[5]={true,true,false},}
AtlasLoot_BonusRoll_Items[86514]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86770]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89967]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86962]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[84980]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86131]={[1]={false,false,true},[2]={false,true,false},[11]={false,false,true,false},[10]={true,false,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[85300]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[85364]={[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[89968]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86963]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84981]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86132]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[89265]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86324]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86388]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[89969]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86964]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84982]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86133]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86325]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[85366]={[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[89842]={[11]={false,true,true,false},[10]={true,true,false},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[89970]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86965]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[84983]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86134]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[90418]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86390]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90738]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[89843]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86838]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89971]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86966]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[84984]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86071]={[10]={true,false,true},[11]={false,true,true,false},}
AtlasLoot_BonusRoll_Items[86135]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89268]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86327]={[11]={false,false,false,true},[7]={false,false,true},[10]={false,true,false},[5]={true,true,false},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86391]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[89972]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86967]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84985]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86136]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86200]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86328]={[8]={true,true,true},[2]={true,false,false},[9]={true,true,true},[10]={false,true,false},}
AtlasLoot_BonusRoll_Items[85369]={[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[90740]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86776]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[89973]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86968]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[84986]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86137]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86201]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[85306]={[11]={true,false,false,false},}
AtlasLoot_BonusRoll_Items[86777]={[10]={true,false,true},[11]={false,true,true,false},}
AtlasLoot_BonusRoll_Items[89974]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86969]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87033]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86138]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86202]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[90422]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[85371]={[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[89783]={[1]={true,true,true},[2]={true,true,true},[3]={true,true,true},[4]={true,true,true},[5]={true,true,true},[6]={true,true,true},[7]={true,true,true},[8]={true,true,true},[9]={true,true,true},[10]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[86778]={[1]={false,false,true},[2]={false,true,false},}
AtlasLoot_BonusRoll_Items[89975]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86970]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87034]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86075]={[1]={false,false,true},[2]={false,true,false},}
AtlasLoot_BonusRoll_Items[86139]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86203]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[90423]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86779]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89976]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86971]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87035]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86076]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86140]={[1]={true,true,false},[2]={false,false,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89273]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[90424]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86780]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89977]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86972]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[87036]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86141]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[89274]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[90425]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86781]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86909]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86973]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87037]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86142]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[89275]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[86334]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86782]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86910]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86974]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[87038]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87166]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[89276]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[85312]={[11]={false,true,false,false},}
AtlasLoot_BonusRoll_Items[85376]={[8]={true,true,true},}
AtlasLoot_BonusRoll_Items[86783]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84801]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89980]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86975]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87039]={[2]={true,false,false},[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86080]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86144]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89277]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86336]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86784]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[84802]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89981]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86976]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87040]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86081]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86145]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89278]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[90429]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85378]={[8]={true,true,true},}
AtlasLoot_BonusRoll_Items[86785]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84803]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89982]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86977]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[87041]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86082]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86146]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86210]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85315]={[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86786]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[84804]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[89983]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86978]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87042]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86083]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86147]={[11]={false,false,false,true},[7]={false,false,true},[10]={false,true,false},[5]={true,true,false},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86211]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90431]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[85380]={[11]={false,false,true,false},}
AtlasLoot_BonusRoll_Items[86787]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84805]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[89984]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86979]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87043]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86084]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86148]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86212]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[90432]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86788]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84806]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89985]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86980]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87044]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86149]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86213]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[90433]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[85382]={[11]={false,false,true,false},}
AtlasLoot_BonusRoll_Items[86789]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[84807]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89986]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86981]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87045]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86086]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86150]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86214]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[90434]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86790]={[1]={false,false,true},[2]={false,true,false},[11]={false,false,true,false},[10]={true,false,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[84808]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86982]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87046]={[10]={true,false,true},[11]={false,true,true,false},}
AtlasLoot_BonusRoll_Items[86151]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85320]={[2]={false,true,false},}
AtlasLoot_BonusRoll_Items[86791]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84809]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86983]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87047]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86152]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86817]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[90436]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[85385]={[10]={true,false,false},}
AtlasLoot_BonusRoll_Items[89960]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86818]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86814]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[89953]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86317]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86792]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[84810]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86815]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86984]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87048]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86911]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87176]={[1]={true,true,false},[2]={false,false,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86217]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86862]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[85322]={[2]={false,true,false},}
AtlasLoot_BonusRoll_Items[87169]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86864]={[10]={true,false,true},[7]={false,true,false},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87823]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[89952]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[90414]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86865]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86793]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[84811]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89271]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86985]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87049]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87150]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87177]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86854]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86863]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[90438]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[85387]={[10]={true,false,false},}
AtlasLoot_BonusRoll_Items[89954]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89958]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89950]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[90840]={[1]={true,true,true},[2]={true,true,true},[3]={true,true,true},[4]={true,true,true},[5]={true,true,true},[6]={true,true,true},[7]={true,true,true},[8]={true,true,true},[9]={true,true,true},[10]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[89922]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86794]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84812]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89925]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86986]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87050]={[1]={false,false,true},[2]={false,true,false},}
AtlasLoot_BonusRoll_Items[89821]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87178]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86219]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89927]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[90439]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[90503]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86949]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[89918]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89935]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86947]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86948]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86795]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84813]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89924]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86987]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[87051]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90413]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87179]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90446]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89926]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[85325]={[1]={false,false,true},}
AtlasLoot_BonusRoll_Items[85389]={[10]={false,true,false},}
AtlasLoot_BonusRoll_Items[89917]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86750]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87020]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[89249]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[89920]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86796]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89929]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87822]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86988]={[10]={true,false,true},[7]={false,true,false},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87052]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84978]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87180]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[89829]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87015]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[90441]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[90505]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[89831]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89822]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89250]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86946]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89802]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86797]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89930]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[89928]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86989]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87053]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89921]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87181]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89919]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89923]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[85327]={[1]={false,false,true},}
AtlasLoot_BonusRoll_Items[90506]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86945]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84975]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89251]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[86159]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89803]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86798]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89931]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87032]={[10]={true,false,true},[7]={false,true,false},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86990]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87054]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86168]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[87182]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[89834]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86160]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[90443]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[90507]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89835]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86156]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86178]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86170]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86329]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86799]={[1]={true,true,false},[2]={false,false,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[84817]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86171]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86991]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87055]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86167]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87183]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86874]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86161]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90444]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[90508]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86157]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89833]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86332]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86153]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86176]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86800]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[84818]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86163]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84946]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[87056]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89836]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87184]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89827]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84952]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85330]={[1]={true,true,false},}
AtlasLoot_BonusRoll_Items[90509]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89242]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[86883]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89830]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86175]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87824]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86801]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84819]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89951]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[84947]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87057]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86204]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87185]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86226]={[10]={true,false,true},[7]={false,true,false},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86166]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[85331]={[1]={true,true,false},}
AtlasLoot_BonusRoll_Items[85395]={[10]={false,false,true},}
AtlasLoot_BonusRoll_Items[86162]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86179]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86158]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86169]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86205]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86802]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84820]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86905]={[1]={true,true,false},[2]={false,false,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[84948]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87058]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[89243]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[87186]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86227]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86901]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[89424]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90511]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86155]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86172]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89837]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86165]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86739]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86803]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84821]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[89828]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[84949]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[87059]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87160]={[1]={false,false,true},[2]={false,true,false},[11]={false,false,true,false},[10]={true,false,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86164]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86228]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[89826]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89425]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85397]={[10]={false,false,true},}
AtlasLoot_BonusRoll_Items[89832]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86154]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86177]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87825]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86740]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86804]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84822]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[84886]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84950]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[87060]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87161]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89234]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[86229]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86878]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[90449]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[90513]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86898]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86879]={[10]={true,false,true},[11]={false,true,true,false},}
AtlasLoot_BonusRoll_Items[86877]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86900]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86741]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86805]={[11]={false,false,false,true},[7]={false,false,true},[10]={false,true,false},[5]={true,true,false},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84823]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84887]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84951]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87061]={[1]={true,true,false},[2]={false,false,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86907]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[89235]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86230]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86908]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[90450]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[90514]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86896]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86892]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86888]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86897]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86742]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86806]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84824]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[84888]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85975]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86039]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86895]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89236]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[86231]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86884]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90451]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[90515]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86875]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86893]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86899]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86890]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86743]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86807]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89940]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[84889]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84953]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86040]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86869]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[89237]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86232]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86882]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[85337]={[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[90516]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86889]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86885]={[11]={false,false,false,true},[7]={false,false,true},[10]={false,true,false},[5]={true,true,false},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86873]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86887]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86744]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86808]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[84826]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84890]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84954]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86041]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86902]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89238]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[86233]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86876]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90453]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[90517]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86886]={[8]={true,true,true},[2]={true,false,false},[9]={true,true,true},[10]={false,true,false},}
AtlasLoot_BonusRoll_Items[86881]={[1]={false,false,true},[2]={false,true,false},[11]={false,false,true,false},[10]={true,false,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86870]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86903]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86745]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86809]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[84827]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84891]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84955]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87065]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86891]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89239]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[86234]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86872]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[90454]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90518]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86906]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86880]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86904]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86868]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86746]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86810]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84828]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84892]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84956]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87066]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86871]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89240]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[87153]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89948]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[85340]={[2]={false,false,true},}
AtlasLoot_BonusRoll_Items[90519]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87156]={[10]={true,false,true},[11]={false,true,true,false},}
AtlasLoot_BonusRoll_Items[87154]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[87175]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87174]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[90839]={[1]={true,true,true},[2]={true,true,true},[3]={true,true,true},[4]={true,true,true},[5]={true,true,true},[6]={true,true,true},[7]={true,true,true},[8]={true,true,true},[9]={true,true,true},[10]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[86811]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84829]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89947]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[84957]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87067]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[87162]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89241]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[90510]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89949]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90456]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[90520]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[87152]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87170]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90504]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[89945]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87771]={[1]={true,true,true},[2]={true,true,true},[3]={true,true,true},[4]={true,true,true},[5]={true,true,true},[6]={true,true,true},[7]={true,true,true},[8]={true,true,true},[9]={true,true,true},[10]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[86812]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84830]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87167]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[84958]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87068]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[90435]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86173]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[87157]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87168]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[85342]={[2]={false,false,true},}
AtlasLoot_BonusRoll_Items[90521]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87163]={[11]={false,false,false,true},[7]={false,false,true},[10]={false,true,false},[5]={true,true,false},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87151]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87165]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90512]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89818]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86813]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[84831]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87155]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85982]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87069]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[87164]={[8]={true,true,true},[2]={true,false,false},[9]={true,true,true},[10]={false,true,false},}
AtlasLoot_BonusRoll_Items[86174]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89946]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87171]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87159]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[90522]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89932]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[87026]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[84825]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87173]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89819]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89883]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[84832]={[11]={false,true,true,false},}
AtlasLoot_BonusRoll_Items[87172]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[84960]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86047]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[87158]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89244]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[85302]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[89933]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86038]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90523]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87027]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84979]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84816]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[87826]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86751]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89884]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[84833]={[11]={false,false,false,true},}
AtlasLoot_BonusRoll_Items[86943]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[85984]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87071]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89934]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89245]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[87028]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85335]={[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[85345]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90524]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86320]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86340]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89839]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87827]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86752]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86816]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84834]={[2]={false,true,true},}
AtlasLoot_BonusRoll_Items[86944]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[85985]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87072]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87029]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89246]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[85990]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86319]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86342]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[90525]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90415]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89936]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86389]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85976]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86753]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89886]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84835]={[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[85922]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[85986]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87073]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[87030]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[89247]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[87062]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[86338]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85347]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90526]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85310]={[11]={false,true,false,false},}
AtlasLoot_BonusRoll_Items[86330]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90416]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[89426]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86754]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[89887]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84836]={[10]={false,true,false},}
AtlasLoot_BonusRoll_Items[85923]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[85987]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[87074]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86339]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89248]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[85977]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[87031]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87063]={[1]={false,false,true},[2]={false,true,false},[11]={false,false,true,false},[10]={true,false,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[90527]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86337]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86326]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90417]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[89938]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86755]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86819]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84837]={[8]={true,true,true},}
AtlasLoot_BonusRoll_Items[85924]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[85988]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[87075]={[11]={false,false,false,true},[7]={false,false,true},[10]={false,true,false},[5]={true,true,false},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85978]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86180]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[87064]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[85285]={[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[90447]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[90528]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89939]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86335]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[85979]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86341]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[86756]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90419]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[84838]={[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85925]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87012]={[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87076]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85980]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86181]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86747]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[86343]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[85350]={[7]={false,false,true},}
AtlasLoot_BonusRoll_Items[90529]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[90420]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[89941]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[84959]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[86331]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86757]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[87017]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84839]={[10]={true,false,true},}
AtlasLoot_BonusRoll_Items[85926]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87013]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87077]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[86748]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86182]={[11]={true,false,false,false},[7]={true,false,false},[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[90421]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[85287]={[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[89942]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[90530]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90448]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[90445]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86749]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86323]={[1]={false,false,true},[2]={false,true,false},[11]={false,false,true,false},[10]={true,false,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86758]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[85983]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[84840]={[1]={true,true,true},}
AtlasLoot_BonusRoll_Items[86950]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[85991]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[87078]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[86333]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89252]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[90455]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87070]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[85352]={[7]={false,false,true},}
AtlasLoot_BonusRoll_Items[86387]={[1]={false,true,true},[2]={false,true,false},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89817]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[86386]={[1]={true,true,false},[2]={false,false,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[85308]={[11]={true,false,false,false},}
AtlasLoot_BonusRoll_Items[89820]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86759]={[1]={true,true,false},[2]={false,false,true},[6]={false,true,true},}
AtlasLoot_BonusRoll_Items[89825]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[84841]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86951]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[85992]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[85989]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89937]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[89253]={[5]={true,true,true},[2]={true,true,true},[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[84976]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[90410]={[10]={false,true,false},[11]={true,false,false,true},}
AtlasLoot_BonusRoll_Items[89823]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[90430]={[11]={true,false,false,true},[7]={true,false,true},[10]={false,true,false},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[90412]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[90452]={[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[87014]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[87016]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86760]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[86027]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84842]={[9]={true,true,true},}
AtlasLoot_BonusRoll_Items[86952]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85993]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[85317]={[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[87144]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[89254]={[1]={true,true,true},[3]={true,true,true},[10]={true,true,true},[7]={true,true,true},}
AtlasLoot_BonusRoll_Items[84977]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[85290]={[7]={true,false,false},}
AtlasLoot_BonusRoll_Items[89824]={[1]={false,false,true},[2]={false,true,false},[6]={true,false,false},}
AtlasLoot_BonusRoll_Items[90440]={[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84814]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[84815]={[8]={true,true,true},[9]={true,true,true},[5]={true,true,true},}
AtlasLoot_BonusRoll_Items[85292]={[7]={true,false,false},}
AtlasLoot_BonusRoll_Items[89766]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86761]={[3]={true,true,true},[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[85995]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84843]={[11]={true,false,false,false},}
AtlasLoot_BonusRoll_Items[86953]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[85994]={[10]={true,false,true},[7]={false,true,false},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[90442]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[87145]={[1]={true,true,true},[2]={false,true,true},[6]={true,true,true},}
AtlasLoot_BonusRoll_Items[89255]={[8]={true,true,true},[6]={true,true,true},[4]={true,true,true},[11]={true,true,true,true},}
AtlasLoot_BonusRoll_Items[85996]={[2]={true,false,false},[7]={true,false,true},}
AtlasLoot_BonusRoll_Items[84972]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84973]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[90437]={[11]={false,true,true,false},[7]={false,true,false},[10]={true,false,true},[4]={true,true,true},[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[86316]={[11]={true,false,false,true},[7]={true,false,true},[8]={true,true,true},[10]={false,true,false},[9]={true,true,true},[5]={true,true,true},[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[85295]={[3]={true,true,true},}
AtlasLoot_BonusRoll_Items[85391]={[10]={false,true,false},}
AtlasLoot_BonusRoll_Items[89767]={[8]={true,true,true},[9]={true,true,true},[5]={false,false,true},}
AtlasLoot_BonusRoll_Items[86762]={[10]={true,false,true},[7]={false,true,false},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[84974]={[2]={true,false,false},}
AtlasLoot_BonusRoll_Items[84844]={[7]={false,true,false},}
AtlasLoot_BonusRoll_Items[86954]={[11]={false,true,true,false},[10]={true,false,true},[4]={true,true,true},}
AtlasLoot_BonusRoll_Items[85361]={[5]={true,true,false},}